global using Microsoft.UI.Xaml;
global using Microsoft.UI.Xaml.Controls;
global using Microsoft.UI.Xaml.Media;
global using Microsoft.UI.Xaml.Input;
global using Windows.Foundation;
global using Windows.System;
global using VectorSpace.Core;
global using VectorSpace.Editing;
global using VectorSpace.Controls;
